---
  title: "Publications"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## in the works
**RY Oliver**, SW Yanco, D Ellis-Soto, BR Jesmer, S Gao, R Patchett, [data providers and additional partners of the COVID-19 Bio-Logging Initiative], C Rutz, W Jetz. Compounding and interacting effects of human activities on wildlife behavior.
*In preparation*

**RY Oliver**, MS Chapman, D Ellis-Soto1, V Brum-Bastos, F Cagnacci, JA Long, M Loretto, R Patchett, C Rutz. Access to human mobility data is essential to building a sustainable future.
*In review at Cell Reports Sustainability*

**RY Oliver**, MS Chapman, N Emery, L Gillespie, N Gownaris, S Leiker, A Nisi, D Ayers, I Breckheimer, H Blondin, AM Hoffman, C Pagniello, M Raisle, N Zimmerman. Opening a conversation on responsible environmental data science in the age of large language models.
*Accepted at Environmental Data Science*

SW Yanco, **RY Oliver**, F Iannarilli, G Heine, U Mueller, N Richter, B Vorneweg, Y Andryushchenko, N Batbayar, B Galtbalt, AE Gavrilov, OA Goroshko, EI Ilyashenko, VY Ilyashenko, EA Mudrik, T Natsagdorj, S Sherub, T Sukhbaatar,  M Wikelski, W Jetz, I Pokrovsky. Migratory birds modulate niche tradeoffs in rhythm with seasons and life history.
*In revision at the Proceedings of the National Academy of Sciences*

M Wikelski, M Quetting, J Bates, G Bohrer, L Börger, T Chapple, M Crofoot, SC Davidson, D Dechmann, D Ellis-Soto, E Ellwood, W Fiedler, A Flack, B Fruth, N Franconi, R Havmoeller, J Hirt, N Hussey, F Iannarilli, M Landwehr, M Mueller, T Müller, U Müller, **RY Oliver**, J Partecke, I Pokrovsky, L Pokrovskaya, D Rubenstein, C Rutz, K Safi, A Santangeli, L van Schalkwyk, A Sequeira, S Sherub, T Ramesh, P Viljoen, K Wasik, T Wild, S Yanco and R Kays. Introducing a unique animal ID and digital life history museum for wildlife metadata.
*In review at Methods in Ecology and Evolution*

E Parker, SR Weiskopf, **RY Oliver**, M Rubenstein, W Jetz. Insufficient and biased representation of species geographic responses to climate change. 
*In revision at Global Change Biology*

## 2023

D Ellis-Soto, **RY Oliver**, V Brum-Bastos, U Demšar, BR Jesmer, JA Long, F Cagnacci, F Ossi, N Queiroz, M Hindell, R Kays, MC Loretto, T Mueller, R Patchett, DW Sims, MA Tucker, Y Ropert-Coudert, C Rutz, W Jetz (2023) A vision for incorporating human mobility in the study of human-wildlife interactions. *Nature Ecology & Evolution*, 1-11.
DOI: https://doi.org/10.1038/s41559-023-02125-6

**RY Oliver**, F Iannarilli, J Ahumada, E Fegraus, N Flores, R Kays, A Ranipeta, MS Rogan, YV Sica, W Jetz (2023) Camera trapping expands the view into global biodiversity and its change. *Philosophical Transactions of the Royal Society B*, 378(1881), 20220232.
DOI: 10.1098/rstb.2022.0232



## 2022
W Jetz, G Tertitski, R Kays, U Mueller, M Wikelski, and supporting authors … **RY Oliver** … (2022)  Biological earth observation with animal sensors. *Trends in Ecology & Evolution*, 37(4), 293-298.
DOI: https://doi.org/10.1016/j.tree.2021.11.011

DM Thomson, AK McEachern, EL Schultz, K Niessen, D Wilken, K Chess, LF Cole, **RY Oliver**, JD Phillips, A Tucker. (2022) Diverse native island flora shows rapid recovery after exotic herbivore removal on Santa Rosa Island, California. *Biological Invasions*, 24(6), 1635-1649.
DOI: https://doi.org/10.1007/s10530-022-02735-4

## 2021
**RY Oliver**, C Meyer, A Ranipeta, K Winner, W Jetz (2021) Global and national trends, gaps, and opportunities in documenting and monitoring species distributions. *PLoS Biology*, 19(8), e3001336.
DOI: https://doi.org/10.1371/journal.pbio.3001336

## 2020
SC Davidson, G Bohrer, E Gurarie, J Jennewein, S LaPoint, PJ Mahoney, NT Boelman, J Eitel, LR Prugh, L Vierling, E Grier, AH Meddens, **RY Oliver**, R Kays, M Wikelski, …, M Hebblewhite. (2020) Ecological insights from three decades of animal movement tracking across a changing Arctic. *Science*, 370(6517), 712-715.
DOI: 10.1126/science.abb7080


**RY Oliver**, PJ Mahoney, E Gurarie, N Krikun, BC Weeks, M Hebblewhite, G Liston, NT Boelman (2020) Behavioral responses to spring snow conditions contribute to long-term shift in migration phenology in American robins. *Environmental Research Letters*, 15(4), 045003.
DOI: https://doi.org/10.1088/1748-9326/ab71a0


## 2019
J Ahumada, E Fegraus, T Birch, N Flores, R Kays, Ti O’Brien, J Palmer, S Schuttler, J Zhoa, W Jetz, M Kinnaird, S Kulkarni, A Lyet, D Thau, M Duong, **RY Oliver**, A Dancer. (2020) Wildlife Insights: A platform to maximize the potential of camera trap and other passive sensor wildlife data for the planet. *Environmental Conservation*, 47(1), 1-6.
DOI: https://doi.org/10.1017/S0376892919000298

## 2018
**RY Oliver**, DPW Ellis, HE Chmura, JS Krasue, JH Pérez, SK Sweet, L Gough, JC Wingfield, NT Boelman (2018) Eavesdropping on the Arctic: Automated bioacoustics reveal dynamics in songbird breeding phenology. *Science Advances*, 4(6), eaaq1084.
DOI: https://doi.org/10.1126/sciadv.aaq1084

## 2017
B Taylor, AE Patterson, M Ajayi, R Arkebauer, K Bao, N Bray, RM Elliott, PPG Gauthier, JGersony, R Gibson, M Guerin, S Lavenhar, C Leland, L Lemordant, W Liao, J Melillo, **RY Oliver**, CM Prager, W Schuster, NB Schwartz, C Shen, K Pavlis Terlizzi, and KL Griffin (2016) Growth and physiology of a dominant understory shrub, Hamamelis virginiana, following canopy disturbance in a temperate hardwood forest. *Canadian Journal of Forest Research*, 47(2), 193-201.
DOI: https://doi.org/10.1139/cjfr-2016-0208

## 2016
TS Magney, JUH Eitel, KL Griffin, NT Boelman, HE Greaves, CM Prager, BA Logan, G Zheng, L Ma, EA Fortin, **RY Oliver**, LA Vierling (2016) LiDAR canopy radiation model reveals patterns of photosynthetic partitioning in an Arctic shrub. *Agricultural and Forest Meteorology*, 221, 78-93. 
DOI: http://dx.doi.org/10.1016/j.agrformet.2016.02.007.

